### ISSUE TITLE
Craft on Danmaku table not work for core bullets

### ISSUE THREAD

**Issue by KotoNekoNya** [Maxmani/arcadian-dream#10]
so problem is if i wanna create bullet from core bullets and put them on table there is nothing on result, but is i put non core bullet its fine
i check the wiki, is this a bug or i do something wrong?
![Screenshot_8](https://github.com/Maxmani/arcadian-dream/assets/96657401/9a3a9c97-ac83-4239-9a7f-7dcdebe325e1)

**Comment by Maxmani** [comment]
You need a Big Power item in the slot you have regular Power items in.

**Comment by KotoNekoNya** [comment]
Oh yes its works) Thanks
