### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by EDTmagiclab** [Maxmani/arcadian-dream#14]
When some people try to play this mod on Android phone(with the help of the HMCL-PE),their game will crashed after they closed the Inventory.And here is the crash report:https://paste.ubuntu.com/p/nPpy82NgMX/

**Comment by Maxmani** [comment]
I really doubt this is caused by this mod. Please try without Arcadian Dream and see if the issue persists. Regardless, I'm not sure there's much I can do to support an unofficial platform.

**Comment by EDTmagiclab** [comment]
The player removed the mod,and the game not crashed again.

**Comment by Maxmani** [comment]
Closing as there's no way for me to support mobile platforms.
