### ISSUE TITLE
Pachouli for In-game documentation

### ISSUE THREAD

**Issue by sorae42** [Maxmani/arcadian-dream#2]
Is it possible to use [Patchouli](https://github.com/VazkiiMods/Patchouli) for in-game documentation?

I can try to port stuff over to Patchouli.

**Comment by Maxmani** [comment]
Yes, I was planning on using Patchouli for the in-game documentation.

**Comment by sorae42** [comment]
I can help you with that if you want to

**Comment by Maxmani** [comment]
Sure thing. I appreciate any and all help!

**Comment by sorae42** [comment]
Close issue until Patchouli 1.19.4 got released.
