### ISSUE TITLE
Will you back port the mod to 1.19.2?

### ISSUE THREAD

**Issue by gundami** [Maxmani/arcadian-dream#4]
As title

**Comment by Maxmani** [comment]
1.19.3 introduced so many breaking changes, that backporting beyond it would not be worth the effort for what is seemingly little gain.

**Comment by Kirisoup** [comment]
I don't blame you but I hate mojang for this.
They've created this barrier which seperates all the exciting 1.19.3 mods from the existing 1.19.2 mod ecosystem...
