### ISSUE TITLE
Elixir Fatigue is able to be removed with milk

### ISSUE THREAD

**Issue by Ryanisstillthesame** [Maxmani/arcadian-dream#7]
Unsure if intentional, but all stages of elixir fatigue are able to be removed instantly by drinking milk

**Comment by Maxmani** [comment]
I did look into this while working on the status effect. Preventing milk from removing a specific effect would be quite hacky, unless I'm missing something. If I can find a good way, I might make milk ignore Elixir Fatigue. Otherwise, this is another aspect of Minecraft we just have to deal with.
